items:
- uid: System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1
  commentId: T:System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1
  id: ConfiguredTaskAwaitable`1
  parent: System.Runtime.CompilerServices
  children:
  - System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.GetAwaiter
  langs:
  - csharp
  - vb
  name: ConfiguredTaskAwaitable<TResult>
  nameWithType: ConfiguredTaskAwaitable<TResult>
  fullName: System.Runtime.CompilerServices.ConfiguredTaskAwaitable<TResult>
  type: Struct
  source:
    remote:
      path: src/System.Threading.Tasks/ref/System.Threading.Tasks.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: ConfiguredTaskAwaitable
    path: src/System.Threading.Tasks/ref/System.Threading.Tasks.cs
    startLine: 87
  assemblies:
  - System.Threading.Tasks
  namespace: System.Runtime.CompilerServices
  syntax:
    content: public struct ConfiguredTaskAwaitable<TResult>
    content.vb: Public Structure ConfiguredTaskAwaitable(Of TResult)
    typeParameters:
    - id: TResult
  nameWithType.vb: ConfiguredTaskAwaitable(Of TResult)
  modifiers.csharp:
  - public
  - struct
  modifiers.vb:
  - Public
  - Structure
  fullName.vb: System.Runtime.CompilerServices.ConfiguredTaskAwaitable(Of TResult)
  name.vb: ConfiguredTaskAwaitable(Of TResult)
- uid: System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.GetAwaiter
  commentId: M:System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.GetAwaiter
  id: GetAwaiter
  parent: System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1
  langs:
  - csharp
  - vb
  name: GetAwaiter()
  nameWithType: ConfiguredTaskAwaitable<TResult>.GetAwaiter()
  fullName: System.Runtime.CompilerServices.ConfiguredTaskAwaitable<TResult>.GetAwaiter()
  type: Method
  source:
    remote:
      path: src/System.Threading.Tasks/ref/System.Threading.Tasks.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: GetAwaiter
    path: src/System.Threading.Tasks/ref/System.Threading.Tasks.cs
    startLine: 90
  assemblies:
  - System.Threading.Tasks
  namespace: System.Runtime.CompilerServices
  syntax:
    content: public ConfiguredTaskAwaitable<TResult>.ConfiguredTaskAwaiter GetAwaiter()
    content.vb: Public Function GetAwaiter As ConfiguredTaskAwaitable(Of TResult).ConfiguredTaskAwaiter
    return:
      type: System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter
  nameWithType.vb: ConfiguredTaskAwaitable(Of TResult).GetAwaiter()
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
  fullName.vb: System.Runtime.CompilerServices.ConfiguredTaskAwaitable(Of TResult).GetAwaiter()
references:
- uid: System.Runtime.CompilerServices
  commentId: N:System.Runtime.CompilerServices
  isExternal: false
  name: System.Runtime.CompilerServices
  nameWithType: System.Runtime.CompilerServices
  fullName: System.Runtime.CompilerServices
- uid: System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter
  commentId: T:System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter
  parent: System.Runtime.CompilerServices
  isExternal: false
  name: ConfiguredTaskAwaitable.ConfiguredTaskAwaiter<>
  nameWithType: ConfiguredTaskAwaitable.ConfiguredTaskAwaiter<>
  fullName: System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter<>
  nameWithType.vb: ConfiguredTaskAwaitable.ConfiguredTaskAwaiter(Of )
  fullname.vb: System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter(Of )
  name.vb: ConfiguredTaskAwaitable.ConfiguredTaskAwaiter(Of )
  spec.csharp:
  - uid: System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter
    name: ConfiguredTaskAwaitable.ConfiguredTaskAwaiter
    nameWithType: ConfiguredTaskAwaitable.ConfiguredTaskAwaiter
    fullName: System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter
  - name: <
    nameWithType: <
    fullName: <
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter
    name: ConfiguredTaskAwaitable.ConfiguredTaskAwaiter
    nameWithType: ConfiguredTaskAwaitable.ConfiguredTaskAwaiter
    fullName: System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: )
    nameWithType: )
    fullName: )
