items:
- uid: System.Diagnostics.Tracing.EventSourceSettings
  commentId: T:System.Diagnostics.Tracing.EventSourceSettings
  id: EventSourceSettings
  parent: System.Diagnostics.Tracing
  children:
  - System.Diagnostics.Tracing.EventSourceSettings.Default
  - System.Diagnostics.Tracing.EventSourceSettings.EtwManifestEventFormat
  - System.Diagnostics.Tracing.EventSourceSettings.EtwSelfDescribingEventFormat
  - System.Diagnostics.Tracing.EventSourceSettings.ThrowOnEventWriteErrors
  langs:
  - csharp
  - vb
  name: EventSourceSettings
  nameWithType: EventSourceSettings
  fullName: System.Diagnostics.Tracing.EventSourceSettings
  type: Enum
  source:
    remote:
      path: src/System.Diagnostics.Tracing/ref/System.Diagnostics.Tracing.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: EventSourceSettings
    path: src/System.Diagnostics.Tracing/ref/System.Diagnostics.Tracing.cs
    startLine: 243
  assemblies:
  - System.Diagnostics.Tracing
  namespace: System.Diagnostics.Tracing
  syntax:
    content: 'public enum EventSourceSettings : int'
    content.vb: Public Enum EventSourceSettings As Integer
  modifiers.csharp:
  - public
  - enum
  modifiers.vb:
  - Public
  - Enum
- uid: System.Diagnostics.Tracing.EventSourceSettings.Default
  commentId: F:System.Diagnostics.Tracing.EventSourceSettings.Default
  id: Default
  parent: System.Diagnostics.Tracing.EventSourceSettings
  langs:
  - csharp
  - vb
  name: Default
  nameWithType: EventSourceSettings.Default
  fullName: System.Diagnostics.Tracing.EventSourceSettings.Default
  type: Field
  source:
    remote:
      path: src/System.Diagnostics.Tracing/ref/System.Diagnostics.Tracing.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: Default
    path: src/System.Diagnostics.Tracing/ref/System.Diagnostics.Tracing.cs
    startLine: 246
  assemblies:
  - System.Diagnostics.Tracing
  namespace: System.Diagnostics.Tracing
  syntax:
    content: Default = null
    content.vb: Default = Nothing
    return:
      type: System.Diagnostics.Tracing.EventSourceSettings
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: System.Diagnostics.Tracing.EventSourceSettings.EtwManifestEventFormat
  commentId: F:System.Diagnostics.Tracing.EventSourceSettings.EtwManifestEventFormat
  id: EtwManifestEventFormat
  parent: System.Diagnostics.Tracing.EventSourceSettings
  langs:
  - csharp
  - vb
  name: EtwManifestEventFormat
  nameWithType: EventSourceSettings.EtwManifestEventFormat
  fullName: System.Diagnostics.Tracing.EventSourceSettings.EtwManifestEventFormat
  type: Field
  source:
    remote:
      path: src/System.Diagnostics.Tracing/ref/System.Diagnostics.Tracing.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: EtwManifestEventFormat
    path: src/System.Diagnostics.Tracing/ref/System.Diagnostics.Tracing.cs
    startLine: 247
  assemblies:
  - System.Diagnostics.Tracing
  namespace: System.Diagnostics.Tracing
  syntax:
    content: EtwManifestEventFormat = null
    content.vb: EtwManifestEventFormat = Nothing
    return:
      type: System.Diagnostics.Tracing.EventSourceSettings
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: System.Diagnostics.Tracing.EventSourceSettings.EtwSelfDescribingEventFormat
  commentId: F:System.Diagnostics.Tracing.EventSourceSettings.EtwSelfDescribingEventFormat
  id: EtwSelfDescribingEventFormat
  parent: System.Diagnostics.Tracing.EventSourceSettings
  langs:
  - csharp
  - vb
  name: EtwSelfDescribingEventFormat
  nameWithType: EventSourceSettings.EtwSelfDescribingEventFormat
  fullName: System.Diagnostics.Tracing.EventSourceSettings.EtwSelfDescribingEventFormat
  type: Field
  source:
    remote:
      path: src/System.Diagnostics.Tracing/ref/System.Diagnostics.Tracing.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: EtwSelfDescribingEventFormat
    path: src/System.Diagnostics.Tracing/ref/System.Diagnostics.Tracing.cs
    startLine: 248
  assemblies:
  - System.Diagnostics.Tracing
  namespace: System.Diagnostics.Tracing
  syntax:
    content: EtwSelfDescribingEventFormat = null
    content.vb: EtwSelfDescribingEventFormat = Nothing
    return:
      type: System.Diagnostics.Tracing.EventSourceSettings
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: System.Diagnostics.Tracing.EventSourceSettings.ThrowOnEventWriteErrors
  commentId: F:System.Diagnostics.Tracing.EventSourceSettings.ThrowOnEventWriteErrors
  id: ThrowOnEventWriteErrors
  parent: System.Diagnostics.Tracing.EventSourceSettings
  langs:
  - csharp
  - vb
  name: ThrowOnEventWriteErrors
  nameWithType: EventSourceSettings.ThrowOnEventWriteErrors
  fullName: System.Diagnostics.Tracing.EventSourceSettings.ThrowOnEventWriteErrors
  type: Field
  source:
    remote:
      path: src/System.Diagnostics.Tracing/ref/System.Diagnostics.Tracing.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: ThrowOnEventWriteErrors
    path: src/System.Diagnostics.Tracing/ref/System.Diagnostics.Tracing.cs
    startLine: 249
  assemblies:
  - System.Diagnostics.Tracing
  namespace: System.Diagnostics.Tracing
  syntax:
    content: ThrowOnEventWriteErrors = null
    content.vb: ThrowOnEventWriteErrors = Nothing
    return:
      type: System.Diagnostics.Tracing.EventSourceSettings
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: System.Diagnostics.Tracing
  commentId: N:System.Diagnostics.Tracing
  isExternal: false
  name: System.Diagnostics.Tracing
  nameWithType: System.Diagnostics.Tracing
  fullName: System.Diagnostics.Tracing
- uid: System.Diagnostics.Tracing.EventSourceSettings
  commentId: T:System.Diagnostics.Tracing.EventSourceSettings
  parent: System.Diagnostics.Tracing
  isExternal: false
  name: EventSourceSettings
  nameWithType: EventSourceSettings
  fullName: System.Diagnostics.Tracing.EventSourceSettings
