items:
- uid: System.Runtime.CompilerServices.ConfiguredTaskAwaitable
  id: ConfiguredTaskAwaitable
  parent: System.Runtime.CompilerServices
  children:
  - System.Runtime.CompilerServices.ConfiguredTaskAwaitable.GetAwaiter
  name: ConfiguredTaskAwaitable
  fullName: System.Runtime.CompilerServices.ConfiguredTaskAwaitable
  type: Struct
  source:
    remote: &o0
      path: src/mscorlib/src/System/Runtime/CompilerServices/TaskAwaiter.cs
      branch: master
      repo: https://github.com/dotnet/coreclr.git
    path: src/mscorlib/src/System/Runtime/CompilerServices/TaskAwaiter.cs
    startLine: 354
  assemblies:
  - System.Threading.Tasks
  namespace: System.Runtime.CompilerServices
  summary: Provides an awaitable object that enables configured awaits on a task.
  syntax:
    content: public struct ConfiguredTaskAwaitable
    content.vb: Public Structure ConfiguredTaskAwaitable
- uid: System.Runtime.CompilerServices.ConfiguredTaskAwaitable.GetAwaiter
  id: GetAwaiter
  parent: System.Runtime.CompilerServices.ConfiguredTaskAwaitable
  name: GetAwaiter()
  fullName: System.Runtime.CompilerServices.ConfiguredTaskAwaitable.GetAwaiter()
  type: Method
  source:
    remote: *o0
    path: src/mscorlib/src/System/Runtime/CompilerServices/TaskAwaiter.cs
    startLine: 372
  assemblies:
  - System.Threading.Tasks
  namespace: System.Runtime.CompilerServices
  summary: Returns an awaiter for this awaitable object.
  syntax:
    content: public ConfiguredTaskAwaitable.ConfiguredTaskAwaiter GetAwaiter()
    content.vb: Public Function GetAwaiter As ConfiguredTaskAwaitable.ConfiguredTaskAwaiter
    return:
      type: System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter
      description: The awaiter.
references:
- uid: System.Runtime.CompilerServices
  isExternal: false
  name: System.Runtime.CompilerServices
  fullName: System.Runtime.CompilerServices
- uid: System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter
  parent: System.Runtime.CompilerServices
  isExternal: false
  name: ConfiguredTaskAwaitable.ConfiguredTaskAwaiter
  fullName: System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter
