items:
- uid: System.Runtime.Serialization.DataContractSerializerSettings
  id: DataContractSerializerSettings
  parent: System.Runtime.Serialization
  children:
  - System.Runtime.Serialization.DataContractSerializerSettings.#ctor
  - System.Runtime.Serialization.DataContractSerializerSettings.DataContractResolver
  - System.Runtime.Serialization.DataContractSerializerSettings.KnownTypes
  - System.Runtime.Serialization.DataContractSerializerSettings.MaxItemsInObjectGraph
  - System.Runtime.Serialization.DataContractSerializerSettings.PreserveObjectReferences
  - System.Runtime.Serialization.DataContractSerializerSettings.RootName
  - System.Runtime.Serialization.DataContractSerializerSettings.RootNamespace
  - System.Runtime.Serialization.DataContractSerializerSettings.SerializeReadOnlyTypes
  name: DataContractSerializerSettings
  fullName: System.Runtime.Serialization.DataContractSerializerSettings
  type: Class
  source:
    remote: &o0
      path: src/System.Private.DataContractSerialization/src/System/Runtime/Serialization/DataContractSerializerSettings.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    path: src/System.Private.DataContractSerialization/src/System/Runtime/Serialization/DataContractSerializerSettings.cs
    startLine: 13
  assemblies:
  - System.Runtime.Serialization.Xml
  namespace: System.Runtime.Serialization
  summary: Specifies data contract serializer settings.
  syntax:
    content: 'public class DataContractSerializerSettings : object'
    content.vb: Public Class DataContractSerializerSettings Inherits Object
  inheritance:
  - System.Object
- uid: System.Runtime.Serialization.DataContractSerializerSettings.#ctor
  id: '#ctor'
  parent: System.Runtime.Serialization.DataContractSerializerSettings
  name: DataContractSerializerSettings()
  fullName: System.Runtime.Serialization.DataContractSerializerSettings.DataContractSerializerSettings()
  type: Constructor
  source:
    remote:
      path: src/System.Runtime.Serialization.Xml/ref/System.Runtime.Serialization.Xml.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    path: src/System.Runtime.Serialization.Xml/ref/System.Runtime.Serialization.Xml.cs
    startLine: 47
  assemblies:
  - System.Runtime.Serialization.Xml
  namespace: System.Runtime.Serialization
  summary: Initializes a new instance of the <xref href="System.Runtime.Serialization.DataContractSerializerSettings" data-throw-if-not-resolved="false"></xref> class.
  syntax:
    content: public DataContractSerializerSettings()
    content.vb: Public Sub New
- uid: System.Runtime.Serialization.DataContractSerializerSettings.DataContractResolver
  id: DataContractResolver
  parent: System.Runtime.Serialization.DataContractSerializerSettings
  name: DataContractResolver
  fullName: System.Runtime.Serialization.DataContractSerializerSettings.DataContractResolver
  type: Property
  source:
    remote: *o0
    path: src/System.Private.DataContractSerialization/src/System/Runtime/Serialization/DataContractSerializerSettings.cs
    startLine: 51
  assemblies:
  - System.Runtime.Serialization.Xml
  namespace: System.Runtime.Serialization
  summary: Gets or sets the component used to dynamically map xsi:type declarations to known contract types.
  syntax:
    content: public DataContractResolver DataContractResolver { get; set; }
    content.vb: Public Property DataContractResolver As DataContractResolver
    parameters: []
    return:
      type: System.Runtime.Serialization.DataContractResolver
      description: The component used to dynamically map xsi:type declarations to known contract types.
- uid: System.Runtime.Serialization.DataContractSerializerSettings.KnownTypes
  id: KnownTypes
  parent: System.Runtime.Serialization.DataContractSerializerSettings
  name: KnownTypes
  fullName: System.Runtime.Serialization.DataContractSerializerSettings.KnownTypes
  type: Property
  source:
    remote: *o0
    path: src/System.Private.DataContractSerialization/src/System/Runtime/Serialization/DataContractSerializerSettings.cs
    startLine: 30
  assemblies:
  - System.Runtime.Serialization.Xml
  namespace: System.Runtime.Serialization
  summary: Gets or sets a collection of types that may be present in the object graph serialized using this instance of the DataContractSerializerSettings.
  syntax:
    content: public Collections.Generic.IEnumerable<Type> KnownTypes { get; set; }
    content.vb: Public Property KnownTypes As Collections.Generic.IEnumerable(Of Type)
    parameters: []
    return:
      type: System.Collections.Generic.IEnumerable{System.Type}
      description: A collection of types that may be present in the object graph serialized using this instance of the DataContractSerializerSettings.
- uid: System.Runtime.Serialization.DataContractSerializerSettings.MaxItemsInObjectGraph
  id: MaxItemsInObjectGraph
  parent: System.Runtime.Serialization.DataContractSerializerSettings
  name: MaxItemsInObjectGraph
  fullName: System.Runtime.Serialization.DataContractSerializerSettings.MaxItemsInObjectGraph
  type: Property
  source:
    remote: *o0
    path: src/System.Private.DataContractSerialization/src/System/Runtime/Serialization/DataContractSerializerSettings.cs
    startLine: 35
  assemblies:
  - System.Runtime.Serialization.Xml
  namespace: System.Runtime.Serialization
  summary: Gets or sets the maximum number of items in an object graph to serialize or deserialize.
  syntax:
    content: public int MaxItemsInObjectGraph { get; set; }
    content.vb: Public Property MaxItemsInObjectGraph As Integer
    parameters: []
    return:
      type: System.Int32
      description: The maximum number of items in an object graph to serialize or deserialize.
- uid: System.Runtime.Serialization.DataContractSerializerSettings.PreserveObjectReferences
  id: PreserveObjectReferences
  parent: System.Runtime.Serialization.DataContractSerializerSettings
  name: PreserveObjectReferences
  fullName: System.Runtime.Serialization.DataContractSerializerSettings.PreserveObjectReferences
  type: Property
  source:
    remote: *o0
    path: src/System.Private.DataContractSerialization/src/System/Runtime/Serialization/DataContractSerializerSettings.cs
    startLine: 45
  assemblies:
  - System.Runtime.Serialization.Xml
  namespace: System.Runtime.Serialization
  summary: Gets or sets a value that specifies whether to use non-standard XML constructs to preserve object reference data.
  syntax:
    content: public bool PreserveObjectReferences { get; set; }
    content.vb: Public Property PreserveObjectReferences As Boolean
    parameters: []
    return:
      type: System.Boolean
      description: True to use non-standard XML constructs to preserve object reference data; otherwise, false.
- uid: System.Runtime.Serialization.DataContractSerializerSettings.RootName
  id: RootName
  parent: System.Runtime.Serialization.DataContractSerializerSettings
  name: RootName
  fullName: System.Runtime.Serialization.DataContractSerializerSettings.RootName
  type: Property
  source:
    remote: *o0
    path: src/System.Private.DataContractSerialization/src/System/Runtime/Serialization/DataContractSerializerSettings.cs
    startLine: 20
  assemblies:
  - System.Runtime.Serialization.Xml
  namespace: System.Runtime.Serialization
  summary: Gets or sets the root name of the selected object.
  syntax:
    content: public XmlDictionaryString RootName { get; set; }
    content.vb: Public Property RootName As XmlDictionaryString
    parameters: []
    return:
      type: System.Xml.XmlDictionaryString
      description: The root name of the selected object.
- uid: System.Runtime.Serialization.DataContractSerializerSettings.RootNamespace
  id: RootNamespace
  parent: System.Runtime.Serialization.DataContractSerializerSettings
  name: RootNamespace
  fullName: System.Runtime.Serialization.DataContractSerializerSettings.RootNamespace
  type: Property
  source:
    remote: *o0
    path: src/System.Private.DataContractSerialization/src/System/Runtime/Serialization/DataContractSerializerSettings.cs
    startLine: 25
  assemblies:
  - System.Runtime.Serialization.Xml
  namespace: System.Runtime.Serialization
  summary: Gets or sets the root namespace for the specified object.
  syntax:
    content: public XmlDictionaryString RootNamespace { get; set; }
    content.vb: Public Property RootNamespace As XmlDictionaryString
    parameters: []
    return:
      type: System.Xml.XmlDictionaryString
      description: The root namespace for the specified object.
- uid: System.Runtime.Serialization.DataContractSerializerSettings.SerializeReadOnlyTypes
  id: SerializeReadOnlyTypes
  parent: System.Runtime.Serialization.DataContractSerializerSettings
  name: SerializeReadOnlyTypes
  fullName: System.Runtime.Serialization.DataContractSerializerSettings.SerializeReadOnlyTypes
  type: Property
  source:
    remote: *o0
    path: src/System.Private.DataContractSerialization/src/System/Runtime/Serialization/DataContractSerializerSettings.cs
    startLine: 56
  assemblies:
  - System.Runtime.Serialization.Xml
  namespace: System.Runtime.Serialization
  summary: Gets or sets a value that specifies whether to serialize read only types.
  syntax:
    content: public bool SerializeReadOnlyTypes { get; set; }
    content.vb: Public Property SerializeReadOnlyTypes As Boolean
    parameters: []
    return:
      type: System.Boolean
      description: True to serialize read only types; otherwise, false.
references:
- uid: System.Runtime.Serialization
  isExternal: false
  name: System.Runtime.Serialization
  fullName: System.Runtime.Serialization
- uid: System.Object
  parent: System
  isExternal: false
  name: Object
  fullName: System.Object
- uid: System
  isExternal: false
  name: System
  fullName: System
- uid: System.Runtime.Serialization.DataContractResolver
  parent: System.Runtime.Serialization
  isExternal: false
  name: DataContractResolver
  fullName: System.Runtime.Serialization.DataContractResolver
- uid: System.Collections.Generic.IEnumerable{System.Type}
  definition: System.Collections.Generic.IEnumerable`1
  name: Collections.Generic.IEnumerable<Type>
  name.vb: Collections.Generic.IEnumerable(Of Type)
  fullName: System.Collections.Generic.IEnumerable<System.Type>
  fullName.vb: System.Collections.Generic.IEnumerable(Of System.Type)
  spec.csharp:
  - uid: System.Collections.Generic.IEnumerable`1
    name: Collections.Generic.IEnumerable
    fullName: System.Collections.Generic.IEnumerable
    isExternal: true
  - name: <
    fullName: <
  - uid: System.Type
    name: Type
    fullName: System.Type
    isExternal: true
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IEnumerable`1
    name: Collections.Generic.IEnumerable
    fullName: System.Collections.Generic.IEnumerable
    isExternal: true
  - name: '(Of '
    fullName: '(Of '
  - uid: System.Type
    name: Type
    fullName: System.Type
    isExternal: true
  - name: )
    fullName: )
- uid: System.Collections.Generic.IEnumerable`1
  parent: System.Collections.Generic
  isExternal: false
  name: Collections.Generic.IEnumerable<>
  name.vb: Collections.Generic.IEnumerable(Of )
  fullName: System.Collections.Generic.IEnumerable<>
  fullName.vb: System.Collections.Generic.IEnumerable(Of )
  spec.csharp:
  - uid: System.Collections.Generic.IEnumerable`1
    name: Collections.Generic.IEnumerable
    fullName: System.Collections.Generic.IEnumerable
  - name: <
    fullName: <
  - {}
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IEnumerable`1
    name: Collections.Generic.IEnumerable
    fullName: System.Collections.Generic.IEnumerable
  - name: '(Of '
    fullName: '(Of '
  - {}
  - name: )
    fullName: )
- uid: System.Collections.Generic
  isExternal: false
  name: System.Collections.Generic
  fullName: System.Collections.Generic
- uid: System.Int32
  parent: System
  isExternal: false
  name: Int32
  fullName: System.Int32
- uid: System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  fullName: System.Boolean
- uid: System.Xml.XmlDictionaryString
  parent: System.Xml
  isExternal: false
  name: XmlDictionaryString
  fullName: System.Xml.XmlDictionaryString
- uid: System.Xml
  isExternal: false
  name: System.Xml
  fullName: System.Xml
