items:
- uid: System.Xml.XmlReaderSettings
  commentId: T:System.Xml.XmlReaderSettings
  id: XmlReaderSettings
  parent: System.Xml
  children:
  - System.Xml.XmlReaderSettings.#ctor
  - System.Xml.XmlReaderSettings.Async
  - System.Xml.XmlReaderSettings.CheckCharacters
  - System.Xml.XmlReaderSettings.Clone
  - System.Xml.XmlReaderSettings.CloseInput
  - System.Xml.XmlReaderSettings.ConformanceLevel
  - System.Xml.XmlReaderSettings.DtdProcessing
  - System.Xml.XmlReaderSettings.IgnoreComments
  - System.Xml.XmlReaderSettings.IgnoreProcessingInstructions
  - System.Xml.XmlReaderSettings.IgnoreWhitespace
  - System.Xml.XmlReaderSettings.LineNumberOffset
  - System.Xml.XmlReaderSettings.LinePositionOffset
  - System.Xml.XmlReaderSettings.MaxCharactersFromEntities
  - System.Xml.XmlReaderSettings.MaxCharactersInDocument
  - System.Xml.XmlReaderSettings.NameTable
  - System.Xml.XmlReaderSettings.Reset
  langs:
  - csharp
  - vb
  name: XmlReaderSettings
  nameWithType: XmlReaderSettings
  fullName: System.Xml.XmlReaderSettings
  type: Class
  source:
    remote:
      path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: XmlReaderSettings
    path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
    startLine: 353
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  syntax:
    content: 'public sealed class XmlReaderSettings : object'
    content.vb: >-
      Public NotInheritable Class XmlReaderSettings
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: System.Xml.XmlReaderSettings.#ctor
  commentId: M:System.Xml.XmlReaderSettings.#ctor
  id: '#ctor'
  parent: System.Xml.XmlReaderSettings
  langs:
  - csharp
  - vb
  name: XmlReaderSettings()
  nameWithType: XmlReaderSettings.XmlReaderSettings()
  fullName: System.Xml.XmlReaderSettings.XmlReaderSettings()
  type: Constructor
  source:
    remote:
      path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: .ctor
    path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
    startLine: 355
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  syntax:
    content: public XmlReaderSettings()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: System.Xml.XmlReaderSettings.Async
  commentId: P:System.Xml.XmlReaderSettings.Async
  id: Async
  parent: System.Xml.XmlReaderSettings
  langs:
  - csharp
  - vb
  name: Async
  nameWithType: XmlReaderSettings.Async
  fullName: System.Xml.XmlReaderSettings.Async
  type: Property
  source:
    remote:
      path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: Async
    path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
    startLine: 356
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  syntax:
    content: public bool Async { get; set; }
    content.vb: Public Property Async As Boolean
    parameters: []
    return:
      type: System.Boolean
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: System.Xml.XmlReaderSettings.CheckCharacters
  commentId: P:System.Xml.XmlReaderSettings.CheckCharacters
  id: CheckCharacters
  parent: System.Xml.XmlReaderSettings
  langs:
  - csharp
  - vb
  name: CheckCharacters
  nameWithType: XmlReaderSettings.CheckCharacters
  fullName: System.Xml.XmlReaderSettings.CheckCharacters
  type: Property
  source:
    remote:
      path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: CheckCharacters
    path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
    startLine: 357
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  syntax:
    content: public bool CheckCharacters { get; set; }
    content.vb: Public Property CheckCharacters As Boolean
    parameters: []
    return:
      type: System.Boolean
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: System.Xml.XmlReaderSettings.CloseInput
  commentId: P:System.Xml.XmlReaderSettings.CloseInput
  id: CloseInput
  parent: System.Xml.XmlReaderSettings
  langs:
  - csharp
  - vb
  name: CloseInput
  nameWithType: XmlReaderSettings.CloseInput
  fullName: System.Xml.XmlReaderSettings.CloseInput
  type: Property
  source:
    remote:
      path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: CloseInput
    path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
    startLine: 358
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  syntax:
    content: public bool CloseInput { get; set; }
    content.vb: Public Property CloseInput As Boolean
    parameters: []
    return:
      type: System.Boolean
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: System.Xml.XmlReaderSettings.ConformanceLevel
  commentId: P:System.Xml.XmlReaderSettings.ConformanceLevel
  id: ConformanceLevel
  parent: System.Xml.XmlReaderSettings
  langs:
  - csharp
  - vb
  name: ConformanceLevel
  nameWithType: XmlReaderSettings.ConformanceLevel
  fullName: System.Xml.XmlReaderSettings.ConformanceLevel
  type: Property
  source:
    remote:
      path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: ConformanceLevel
    path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
    startLine: 359
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  syntax:
    content: public ConformanceLevel ConformanceLevel { get; set; }
    content.vb: Public Property ConformanceLevel As ConformanceLevel
    parameters: []
    return:
      type: System.Xml.ConformanceLevel
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: System.Xml.XmlReaderSettings.DtdProcessing
  commentId: P:System.Xml.XmlReaderSettings.DtdProcessing
  id: DtdProcessing
  parent: System.Xml.XmlReaderSettings
  langs:
  - csharp
  - vb
  name: DtdProcessing
  nameWithType: XmlReaderSettings.DtdProcessing
  fullName: System.Xml.XmlReaderSettings.DtdProcessing
  type: Property
  source:
    remote:
      path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: DtdProcessing
    path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
    startLine: 360
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  syntax:
    content: public DtdProcessing DtdProcessing { get; set; }
    content.vb: Public Property DtdProcessing As DtdProcessing
    parameters: []
    return:
      type: System.Xml.DtdProcessing
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: System.Xml.XmlReaderSettings.IgnoreComments
  commentId: P:System.Xml.XmlReaderSettings.IgnoreComments
  id: IgnoreComments
  parent: System.Xml.XmlReaderSettings
  langs:
  - csharp
  - vb
  name: IgnoreComments
  nameWithType: XmlReaderSettings.IgnoreComments
  fullName: System.Xml.XmlReaderSettings.IgnoreComments
  type: Property
  source:
    remote:
      path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: IgnoreComments
    path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
    startLine: 361
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  syntax:
    content: public bool IgnoreComments { get; set; }
    content.vb: Public Property IgnoreComments As Boolean
    parameters: []
    return:
      type: System.Boolean
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: System.Xml.XmlReaderSettings.IgnoreProcessingInstructions
  commentId: P:System.Xml.XmlReaderSettings.IgnoreProcessingInstructions
  id: IgnoreProcessingInstructions
  parent: System.Xml.XmlReaderSettings
  langs:
  - csharp
  - vb
  name: IgnoreProcessingInstructions
  nameWithType: XmlReaderSettings.IgnoreProcessingInstructions
  fullName: System.Xml.XmlReaderSettings.IgnoreProcessingInstructions
  type: Property
  source:
    remote:
      path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: IgnoreProcessingInstructions
    path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
    startLine: 362
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  syntax:
    content: public bool IgnoreProcessingInstructions { get; set; }
    content.vb: Public Property IgnoreProcessingInstructions As Boolean
    parameters: []
    return:
      type: System.Boolean
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: System.Xml.XmlReaderSettings.IgnoreWhitespace
  commentId: P:System.Xml.XmlReaderSettings.IgnoreWhitespace
  id: IgnoreWhitespace
  parent: System.Xml.XmlReaderSettings
  langs:
  - csharp
  - vb
  name: IgnoreWhitespace
  nameWithType: XmlReaderSettings.IgnoreWhitespace
  fullName: System.Xml.XmlReaderSettings.IgnoreWhitespace
  type: Property
  source:
    remote:
      path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: IgnoreWhitespace
    path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
    startLine: 363
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  syntax:
    content: public bool IgnoreWhitespace { get; set; }
    content.vb: Public Property IgnoreWhitespace As Boolean
    parameters: []
    return:
      type: System.Boolean
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: System.Xml.XmlReaderSettings.LineNumberOffset
  commentId: P:System.Xml.XmlReaderSettings.LineNumberOffset
  id: LineNumberOffset
  parent: System.Xml.XmlReaderSettings
  langs:
  - csharp
  - vb
  name: LineNumberOffset
  nameWithType: XmlReaderSettings.LineNumberOffset
  fullName: System.Xml.XmlReaderSettings.LineNumberOffset
  type: Property
  source:
    remote:
      path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: LineNumberOffset
    path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
    startLine: 364
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  syntax:
    content: public int LineNumberOffset { get; set; }
    content.vb: Public Property LineNumberOffset As Integer
    parameters: []
    return:
      type: System.Int32
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: System.Xml.XmlReaderSettings.LinePositionOffset
  commentId: P:System.Xml.XmlReaderSettings.LinePositionOffset
  id: LinePositionOffset
  parent: System.Xml.XmlReaderSettings
  langs:
  - csharp
  - vb
  name: LinePositionOffset
  nameWithType: XmlReaderSettings.LinePositionOffset
  fullName: System.Xml.XmlReaderSettings.LinePositionOffset
  type: Property
  source:
    remote:
      path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: LinePositionOffset
    path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
    startLine: 365
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  syntax:
    content: public int LinePositionOffset { get; set; }
    content.vb: Public Property LinePositionOffset As Integer
    parameters: []
    return:
      type: System.Int32
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: System.Xml.XmlReaderSettings.MaxCharactersFromEntities
  commentId: P:System.Xml.XmlReaderSettings.MaxCharactersFromEntities
  id: MaxCharactersFromEntities
  parent: System.Xml.XmlReaderSettings
  langs:
  - csharp
  - vb
  name: MaxCharactersFromEntities
  nameWithType: XmlReaderSettings.MaxCharactersFromEntities
  fullName: System.Xml.XmlReaderSettings.MaxCharactersFromEntities
  type: Property
  source:
    remote:
      path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: MaxCharactersFromEntities
    path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
    startLine: 366
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  syntax:
    content: public long MaxCharactersFromEntities { get; set; }
    content.vb: Public Property MaxCharactersFromEntities As Long
    parameters: []
    return:
      type: System.Int64
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: System.Xml.XmlReaderSettings.MaxCharactersInDocument
  commentId: P:System.Xml.XmlReaderSettings.MaxCharactersInDocument
  id: MaxCharactersInDocument
  parent: System.Xml.XmlReaderSettings
  langs:
  - csharp
  - vb
  name: MaxCharactersInDocument
  nameWithType: XmlReaderSettings.MaxCharactersInDocument
  fullName: System.Xml.XmlReaderSettings.MaxCharactersInDocument
  type: Property
  source:
    remote:
      path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: MaxCharactersInDocument
    path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
    startLine: 367
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  syntax:
    content: public long MaxCharactersInDocument { get; set; }
    content.vb: Public Property MaxCharactersInDocument As Long
    parameters: []
    return:
      type: System.Int64
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: System.Xml.XmlReaderSettings.NameTable
  commentId: P:System.Xml.XmlReaderSettings.NameTable
  id: NameTable
  parent: System.Xml.XmlReaderSettings
  langs:
  - csharp
  - vb
  name: NameTable
  nameWithType: XmlReaderSettings.NameTable
  fullName: System.Xml.XmlReaderSettings.NameTable
  type: Property
  source:
    remote:
      path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: NameTable
    path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
    startLine: 368
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  syntax:
    content: public XmlNameTable NameTable { get; set; }
    content.vb: Public Property NameTable As XmlNameTable
    parameters: []
    return:
      type: System.Xml.XmlNameTable
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: System.Xml.XmlReaderSettings.Clone
  commentId: M:System.Xml.XmlReaderSettings.Clone
  id: Clone
  parent: System.Xml.XmlReaderSettings
  langs:
  - csharp
  - vb
  name: Clone()
  nameWithType: XmlReaderSettings.Clone()
  fullName: System.Xml.XmlReaderSettings.Clone()
  type: Method
  source:
    remote:
      path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: Clone
    path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
    startLine: 369
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  syntax:
    content: public XmlReaderSettings Clone()
    content.vb: Public Function Clone As XmlReaderSettings
    return:
      type: System.Xml.XmlReaderSettings
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: System.Xml.XmlReaderSettings.Reset
  commentId: M:System.Xml.XmlReaderSettings.Reset
  id: Reset
  parent: System.Xml.XmlReaderSettings
  langs:
  - csharp
  - vb
  name: Reset()
  nameWithType: XmlReaderSettings.Reset()
  fullName: System.Xml.XmlReaderSettings.Reset()
  type: Method
  source:
    remote:
      path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: Reset
    path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
    startLine: 370
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  syntax:
    content: public void Reset()
    content.vb: Public Sub Reset
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: System.Xml
  commentId: N:System.Xml
  isExternal: false
  name: System.Xml
  nameWithType: System.Xml
  fullName: System.Xml
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Xml.ConformanceLevel
  commentId: T:System.Xml.ConformanceLevel
  parent: System.Xml
  isExternal: false
  name: ConformanceLevel
  nameWithType: ConformanceLevel
  fullName: System.Xml.ConformanceLevel
- uid: System.Xml.DtdProcessing
  commentId: T:System.Xml.DtdProcessing
  parent: System.Xml
  isExternal: false
  name: DtdProcessing
  nameWithType: DtdProcessing
  fullName: System.Xml.DtdProcessing
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: false
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Int64
  commentId: T:System.Int64
  parent: System
  isExternal: false
  name: Int64
  nameWithType: Int64
  fullName: System.Int64
- uid: System.Xml.XmlNameTable
  commentId: T:System.Xml.XmlNameTable
  parent: System.Xml
  isExternal: false
  name: XmlNameTable
  nameWithType: XmlNameTable
  fullName: System.Xml.XmlNameTable
- uid: System.Xml.XmlReaderSettings
  commentId: T:System.Xml.XmlReaderSettings
  parent: System.Xml
  isExternal: false
  name: XmlReaderSettings
  nameWithType: XmlReaderSettings
  fullName: System.Xml.XmlReaderSettings
