items:
- uid: System.Xml.XmlWriterSettings
  commentId: T:System.Xml.XmlWriterSettings
  id: XmlWriterSettings
  parent: System.Xml
  children:
  - System.Xml.XmlWriterSettings.#ctor
  - System.Xml.XmlWriterSettings.Async
  - System.Xml.XmlWriterSettings.CheckCharacters
  - System.Xml.XmlWriterSettings.Clone
  - System.Xml.XmlWriterSettings.CloseOutput
  - System.Xml.XmlWriterSettings.ConformanceLevel
  - System.Xml.XmlWriterSettings.Encoding
  - System.Xml.XmlWriterSettings.Indent
  - System.Xml.XmlWriterSettings.IndentChars
  - System.Xml.XmlWriterSettings.NamespaceHandling
  - System.Xml.XmlWriterSettings.NewLineChars
  - System.Xml.XmlWriterSettings.NewLineHandling
  - System.Xml.XmlWriterSettings.NewLineOnAttributes
  - System.Xml.XmlWriterSettings.OmitXmlDeclaration
  - System.Xml.XmlWriterSettings.Reset
  - System.Xml.XmlWriterSettings.WriteEndDocumentOnClose
  langs:
  - csharp
  - vb
  name: XmlWriterSettings
  nameWithType: XmlWriterSettings
  fullName: System.Xml.XmlWriterSettings
  type: Class
  source:
    remote:
      path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: XmlWriterSettings
    path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
    startLine: 475
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  syntax:
    content: 'public sealed class XmlWriterSettings : object'
    content.vb: >-
      Public NotInheritable Class XmlWriterSettings
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - sealed
  - class
  modifiers.vb:
  - Public
  - NotInheritable
  - Class
- uid: System.Xml.XmlWriterSettings.#ctor
  commentId: M:System.Xml.XmlWriterSettings.#ctor
  id: '#ctor'
  parent: System.Xml.XmlWriterSettings
  langs:
  - csharp
  - vb
  name: XmlWriterSettings()
  nameWithType: XmlWriterSettings.XmlWriterSettings()
  fullName: System.Xml.XmlWriterSettings.XmlWriterSettings()
  type: Constructor
  source:
    remote:
      path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: .ctor
    path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
    startLine: 477
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  syntax:
    content: public XmlWriterSettings()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: System.Xml.XmlWriterSettings.Async
  commentId: P:System.Xml.XmlWriterSettings.Async
  id: Async
  parent: System.Xml.XmlWriterSettings
  langs:
  - csharp
  - vb
  name: Async
  nameWithType: XmlWriterSettings.Async
  fullName: System.Xml.XmlWriterSettings.Async
  type: Property
  source:
    remote:
      path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: Async
    path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
    startLine: 478
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  syntax:
    content: public bool Async { get; set; }
    content.vb: Public Property Async As Boolean
    parameters: []
    return:
      type: System.Boolean
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: System.Xml.XmlWriterSettings.CheckCharacters
  commentId: P:System.Xml.XmlWriterSettings.CheckCharacters
  id: CheckCharacters
  parent: System.Xml.XmlWriterSettings
  langs:
  - csharp
  - vb
  name: CheckCharacters
  nameWithType: XmlWriterSettings.CheckCharacters
  fullName: System.Xml.XmlWriterSettings.CheckCharacters
  type: Property
  source:
    remote:
      path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: CheckCharacters
    path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
    startLine: 479
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  syntax:
    content: public bool CheckCharacters { get; set; }
    content.vb: Public Property CheckCharacters As Boolean
    parameters: []
    return:
      type: System.Boolean
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: System.Xml.XmlWriterSettings.CloseOutput
  commentId: P:System.Xml.XmlWriterSettings.CloseOutput
  id: CloseOutput
  parent: System.Xml.XmlWriterSettings
  langs:
  - csharp
  - vb
  name: CloseOutput
  nameWithType: XmlWriterSettings.CloseOutput
  fullName: System.Xml.XmlWriterSettings.CloseOutput
  type: Property
  source:
    remote:
      path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: CloseOutput
    path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
    startLine: 480
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  syntax:
    content: public bool CloseOutput { get; set; }
    content.vb: Public Property CloseOutput As Boolean
    parameters: []
    return:
      type: System.Boolean
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: System.Xml.XmlWriterSettings.ConformanceLevel
  commentId: P:System.Xml.XmlWriterSettings.ConformanceLevel
  id: ConformanceLevel
  parent: System.Xml.XmlWriterSettings
  langs:
  - csharp
  - vb
  name: ConformanceLevel
  nameWithType: XmlWriterSettings.ConformanceLevel
  fullName: System.Xml.XmlWriterSettings.ConformanceLevel
  type: Property
  source:
    remote:
      path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: ConformanceLevel
    path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
    startLine: 481
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  syntax:
    content: public ConformanceLevel ConformanceLevel { get; set; }
    content.vb: Public Property ConformanceLevel As ConformanceLevel
    parameters: []
    return:
      type: System.Xml.ConformanceLevel
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: System.Xml.XmlWriterSettings.Encoding
  commentId: P:System.Xml.XmlWriterSettings.Encoding
  id: Encoding
  parent: System.Xml.XmlWriterSettings
  langs:
  - csharp
  - vb
  name: Encoding
  nameWithType: XmlWriterSettings.Encoding
  fullName: System.Xml.XmlWriterSettings.Encoding
  type: Property
  source:
    remote:
      path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: Encoding
    path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
    startLine: 482
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  syntax:
    content: public Text.Encoding Encoding { get; set; }
    content.vb: Public Property Encoding As Text.Encoding
    parameters: []
    return:
      type: System.Text.Encoding
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: System.Xml.XmlWriterSettings.Indent
  commentId: P:System.Xml.XmlWriterSettings.Indent
  id: Indent
  parent: System.Xml.XmlWriterSettings
  langs:
  - csharp
  - vb
  name: Indent
  nameWithType: XmlWriterSettings.Indent
  fullName: System.Xml.XmlWriterSettings.Indent
  type: Property
  source:
    remote:
      path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: Indent
    path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
    startLine: 483
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  syntax:
    content: public bool Indent { get; set; }
    content.vb: Public Property Indent As Boolean
    parameters: []
    return:
      type: System.Boolean
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: System.Xml.XmlWriterSettings.IndentChars
  commentId: P:System.Xml.XmlWriterSettings.IndentChars
  id: IndentChars
  parent: System.Xml.XmlWriterSettings
  langs:
  - csharp
  - vb
  name: IndentChars
  nameWithType: XmlWriterSettings.IndentChars
  fullName: System.Xml.XmlWriterSettings.IndentChars
  type: Property
  source:
    remote:
      path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: IndentChars
    path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
    startLine: 484
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  syntax:
    content: public string IndentChars { get; set; }
    content.vb: Public Property IndentChars As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: System.Xml.XmlWriterSettings.NamespaceHandling
  commentId: P:System.Xml.XmlWriterSettings.NamespaceHandling
  id: NamespaceHandling
  parent: System.Xml.XmlWriterSettings
  langs:
  - csharp
  - vb
  name: NamespaceHandling
  nameWithType: XmlWriterSettings.NamespaceHandling
  fullName: System.Xml.XmlWriterSettings.NamespaceHandling
  type: Property
  source:
    remote:
      path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: NamespaceHandling
    path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
    startLine: 485
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  syntax:
    content: public NamespaceHandling NamespaceHandling { get; set; }
    content.vb: Public Property NamespaceHandling As NamespaceHandling
    parameters: []
    return:
      type: System.Xml.NamespaceHandling
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: System.Xml.XmlWriterSettings.NewLineChars
  commentId: P:System.Xml.XmlWriterSettings.NewLineChars
  id: NewLineChars
  parent: System.Xml.XmlWriterSettings
  langs:
  - csharp
  - vb
  name: NewLineChars
  nameWithType: XmlWriterSettings.NewLineChars
  fullName: System.Xml.XmlWriterSettings.NewLineChars
  type: Property
  source:
    remote:
      path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: NewLineChars
    path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
    startLine: 486
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  syntax:
    content: public string NewLineChars { get; set; }
    content.vb: Public Property NewLineChars As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: System.Xml.XmlWriterSettings.NewLineHandling
  commentId: P:System.Xml.XmlWriterSettings.NewLineHandling
  id: NewLineHandling
  parent: System.Xml.XmlWriterSettings
  langs:
  - csharp
  - vb
  name: NewLineHandling
  nameWithType: XmlWriterSettings.NewLineHandling
  fullName: System.Xml.XmlWriterSettings.NewLineHandling
  type: Property
  source:
    remote:
      path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: NewLineHandling
    path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
    startLine: 487
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  syntax:
    content: public NewLineHandling NewLineHandling { get; set; }
    content.vb: Public Property NewLineHandling As NewLineHandling
    parameters: []
    return:
      type: System.Xml.NewLineHandling
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: System.Xml.XmlWriterSettings.NewLineOnAttributes
  commentId: P:System.Xml.XmlWriterSettings.NewLineOnAttributes
  id: NewLineOnAttributes
  parent: System.Xml.XmlWriterSettings
  langs:
  - csharp
  - vb
  name: NewLineOnAttributes
  nameWithType: XmlWriterSettings.NewLineOnAttributes
  fullName: System.Xml.XmlWriterSettings.NewLineOnAttributes
  type: Property
  source:
    remote:
      path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: NewLineOnAttributes
    path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
    startLine: 488
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  syntax:
    content: public bool NewLineOnAttributes { get; set; }
    content.vb: Public Property NewLineOnAttributes As Boolean
    parameters: []
    return:
      type: System.Boolean
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: System.Xml.XmlWriterSettings.OmitXmlDeclaration
  commentId: P:System.Xml.XmlWriterSettings.OmitXmlDeclaration
  id: OmitXmlDeclaration
  parent: System.Xml.XmlWriterSettings
  langs:
  - csharp
  - vb
  name: OmitXmlDeclaration
  nameWithType: XmlWriterSettings.OmitXmlDeclaration
  fullName: System.Xml.XmlWriterSettings.OmitXmlDeclaration
  type: Property
  source:
    remote:
      path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: OmitXmlDeclaration
    path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
    startLine: 489
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  syntax:
    content: public bool OmitXmlDeclaration { get; set; }
    content.vb: Public Property OmitXmlDeclaration As Boolean
    parameters: []
    return:
      type: System.Boolean
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: System.Xml.XmlWriterSettings.WriteEndDocumentOnClose
  commentId: P:System.Xml.XmlWriterSettings.WriteEndDocumentOnClose
  id: WriteEndDocumentOnClose
  parent: System.Xml.XmlWriterSettings
  langs:
  - csharp
  - vb
  name: WriteEndDocumentOnClose
  nameWithType: XmlWriterSettings.WriteEndDocumentOnClose
  fullName: System.Xml.XmlWriterSettings.WriteEndDocumentOnClose
  type: Property
  source:
    remote:
      path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: WriteEndDocumentOnClose
    path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
    startLine: 490
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  syntax:
    content: public bool WriteEndDocumentOnClose { get; set; }
    content.vb: Public Property WriteEndDocumentOnClose As Boolean
    parameters: []
    return:
      type: System.Boolean
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: System.Xml.XmlWriterSettings.Clone
  commentId: M:System.Xml.XmlWriterSettings.Clone
  id: Clone
  parent: System.Xml.XmlWriterSettings
  langs:
  - csharp
  - vb
  name: Clone()
  nameWithType: XmlWriterSettings.Clone()
  fullName: System.Xml.XmlWriterSettings.Clone()
  type: Method
  source:
    remote:
      path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: Clone
    path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
    startLine: 491
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  syntax:
    content: public XmlWriterSettings Clone()
    content.vb: Public Function Clone As XmlWriterSettings
    return:
      type: System.Xml.XmlWriterSettings
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: System.Xml.XmlWriterSettings.Reset
  commentId: M:System.Xml.XmlWriterSettings.Reset
  id: Reset
  parent: System.Xml.XmlWriterSettings
  langs:
  - csharp
  - vb
  name: Reset()
  nameWithType: XmlWriterSettings.Reset()
  fullName: System.Xml.XmlWriterSettings.Reset()
  type: Method
  source:
    remote:
      path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: Reset
    path: src/System.Xml.ReaderWriter/ref/System.Xml.ReaderWriter.cs
    startLine: 492
  assemblies:
  - System.Xml.ReaderWriter
  namespace: System.Xml
  syntax:
    content: public void Reset()
    content.vb: Public Sub Reset
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: System.Xml
  commentId: N:System.Xml
  isExternal: false
  name: System.Xml
  nameWithType: System.Xml
  fullName: System.Xml
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Xml.ConformanceLevel
  commentId: T:System.Xml.ConformanceLevel
  parent: System.Xml
  isExternal: false
  name: ConformanceLevel
  nameWithType: ConformanceLevel
  fullName: System.Xml.ConformanceLevel
- uid: System.Text.Encoding
  commentId: T:System.Text.Encoding
  parent: System.Text
  isExternal: false
  name: Encoding
  nameWithType: Encoding
  fullName: System.Text.Encoding
- uid: System.Text
  commentId: N:System.Text
  isExternal: false
  name: System.Text
  nameWithType: System.Text
  fullName: System.Text
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Xml.NamespaceHandling
  commentId: T:System.Xml.NamespaceHandling
  parent: System.Xml
  isExternal: false
  name: NamespaceHandling
  nameWithType: NamespaceHandling
  fullName: System.Xml.NamespaceHandling
- uid: System.Xml.NewLineHandling
  commentId: T:System.Xml.NewLineHandling
  parent: System.Xml
  isExternal: false
  name: NewLineHandling
  nameWithType: NewLineHandling
  fullName: System.Xml.NewLineHandling
- uid: System.Xml.XmlWriterSettings
  commentId: T:System.Xml.XmlWriterSettings
  parent: System.Xml
  isExternal: false
  name: XmlWriterSettings
  nameWithType: XmlWriterSettings
  fullName: System.Xml.XmlWriterSettings
