items:
- uid: System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1
  id: ConfiguredTaskAwaitable`1
  parent: System.Runtime.CompilerServices
  children:
  - System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.GetAwaiter
  name: ConfiguredTaskAwaitable<TResult>
  name.vb: ConfiguredTaskAwaitable(Of TResult)
  fullName: System.Runtime.CompilerServices.ConfiguredTaskAwaitable<TResult>
  fullName.vb: System.Runtime.CompilerServices.ConfiguredTaskAwaitable(Of TResult)
  type: Struct
  source:
    remote: &o0
      path: src/mscorlib/src/System/Runtime/CompilerServices/TaskAwaiter.cs
      branch: master
      repo: https://github.com/dotnet/coreclr.git
    path: src/mscorlib/src/System/Runtime/CompilerServices/TaskAwaiter.cs
    startLine: 444
  assemblies:
  - System.Threading.Tasks
  namespace: System.Runtime.CompilerServices
  summary: Provides an awaitable object that enables configured awaits on a task.
  syntax:
    content: public struct ConfiguredTaskAwaitable<TResult>
    content.vb: Public Structure ConfiguredTaskAwaitable(Of TResult)
    typeParameters:
    - id: TResult
- uid: System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.GetAwaiter
  id: GetAwaiter
  parent: System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1
  name: GetAwaiter()
  fullName: System.Runtime.CompilerServices.ConfiguredTaskAwaitable<TResult>.GetAwaiter()
  fullName.vb: System.Runtime.CompilerServices.ConfiguredTaskAwaitable(Of TResult).GetAwaiter()
  type: Method
  source:
    remote: *o0
    path: src/mscorlib/src/System/Runtime/CompilerServices/TaskAwaiter.cs
    startLine: 461
  assemblies:
  - System.Threading.Tasks
  namespace: System.Runtime.CompilerServices
  summary: Returns an awaiter for this awaitable object.
  syntax:
    content: public ConfiguredTaskAwaitable<TResult>.ConfiguredTaskAwaiter GetAwaiter()
    content.vb: Public Function GetAwaiter As ConfiguredTaskAwaitable(Of TResult).ConfiguredTaskAwaiter
    return:
      type: System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter
      description: The awaiter.
references:
- uid: System.Runtime.CompilerServices
  isExternal: false
  name: System.Runtime.CompilerServices
  fullName: System.Runtime.CompilerServices
- uid: System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter
  parent: System.Runtime.CompilerServices
  isExternal: false
  name: ConfiguredTaskAwaitable.ConfiguredTaskAwaiter<>
  name.vb: ConfiguredTaskAwaitable.ConfiguredTaskAwaiter(Of )
  fullName: System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter<>
  fullName.vb: System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter(Of )
  spec.csharp:
  - uid: System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter
    name: ConfiguredTaskAwaitable.ConfiguredTaskAwaiter
    fullName: System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter
  - name: <
    fullName: <
  - name: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter
    name: ConfiguredTaskAwaitable.ConfiguredTaskAwaiter
    fullName: System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter
  - name: '(Of '
    fullName: '(Of '
  - name: )
    fullName: )
