items:
- uid: System.Data.SqlClient.ApplicationIntent
  commentId: T:System.Data.SqlClient.ApplicationIntent
  id: ApplicationIntent
  parent: System.Data.SqlClient
  children:
  - System.Data.SqlClient.ApplicationIntent.ReadOnly
  - System.Data.SqlClient.ApplicationIntent.ReadWrite
  langs:
  - csharp
  - vb
  name: ApplicationIntent
  nameWithType: ApplicationIntent
  fullName: System.Data.SqlClient.ApplicationIntent
  type: Enum
  source:
    remote:
      path: src/System.Data.SqlClient/ref/System.Data.SqlClient.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: ApplicationIntent
    path: src/System.Data.SqlClient/ref/System.Data.SqlClient.cs
    startLine: 207
  assemblies:
  - System.Data.SqlClient
  namespace: System.Data.SqlClient
  syntax:
    content: 'public enum ApplicationIntent : int'
    content.vb: Public Enum ApplicationIntent As Integer
  modifiers.csharp:
  - public
  - enum
  modifiers.vb:
  - Public
  - Enum
- uid: System.Data.SqlClient.ApplicationIntent.ReadOnly
  commentId: F:System.Data.SqlClient.ApplicationIntent.ReadOnly
  id: ReadOnly
  parent: System.Data.SqlClient.ApplicationIntent
  langs:
  - csharp
  - vb
  name: ReadOnly
  nameWithType: ApplicationIntent.ReadOnly
  fullName: System.Data.SqlClient.ApplicationIntent.ReadOnly
  type: Field
  source:
    remote:
      path: src/System.Data.SqlClient/ref/System.Data.SqlClient.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: ReadOnly
    path: src/System.Data.SqlClient/ref/System.Data.SqlClient.cs
    startLine: 209
  assemblies:
  - System.Data.SqlClient
  namespace: System.Data.SqlClient
  syntax:
    content: ReadOnly = null
    content.vb: ReadOnly = Nothing
    return:
      type: System.Data.SqlClient.ApplicationIntent
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: System.Data.SqlClient.ApplicationIntent.ReadWrite
  commentId: F:System.Data.SqlClient.ApplicationIntent.ReadWrite
  id: ReadWrite
  parent: System.Data.SqlClient.ApplicationIntent
  langs:
  - csharp
  - vb
  name: ReadWrite
  nameWithType: ApplicationIntent.ReadWrite
  fullName: System.Data.SqlClient.ApplicationIntent.ReadWrite
  type: Field
  source:
    remote:
      path: src/System.Data.SqlClient/ref/System.Data.SqlClient.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: ReadWrite
    path: src/System.Data.SqlClient/ref/System.Data.SqlClient.cs
    startLine: 210
  assemblies:
  - System.Data.SqlClient
  namespace: System.Data.SqlClient
  syntax:
    content: ReadWrite = null
    content.vb: ReadWrite = Nothing
    return:
      type: System.Data.SqlClient.ApplicationIntent
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: System.Data.SqlClient
  commentId: N:System.Data.SqlClient
  isExternal: false
  name: System.Data.SqlClient
  nameWithType: System.Data.SqlClient
  fullName: System.Data.SqlClient
- uid: System.Data.SqlClient.ApplicationIntent
  commentId: T:System.Data.SqlClient.ApplicationIntent
  parent: System.Data.SqlClient
  isExternal: false
  name: ApplicationIntent
  nameWithType: ApplicationIntent
  fullName: System.Data.SqlClient.ApplicationIntent
