items:
- uid: System.Runtime.Serialization.Json.DataContractJsonSerializerSettings
  commentId: T:System.Runtime.Serialization.Json.DataContractJsonSerializerSettings
  id: DataContractJsonSerializerSettings
  parent: System.Runtime.Serialization.Json
  children:
  - System.Runtime.Serialization.Json.DataContractJsonSerializerSettings.#ctor
  - System.Runtime.Serialization.Json.DataContractJsonSerializerSettings.DateTimeFormat
  - System.Runtime.Serialization.Json.DataContractJsonSerializerSettings.EmitTypeInformation
  - System.Runtime.Serialization.Json.DataContractJsonSerializerSettings.KnownTypes
  - System.Runtime.Serialization.Json.DataContractJsonSerializerSettings.MaxItemsInObjectGraph
  - System.Runtime.Serialization.Json.DataContractJsonSerializerSettings.RootName
  - System.Runtime.Serialization.Json.DataContractJsonSerializerSettings.SerializeReadOnlyTypes
  - System.Runtime.Serialization.Json.DataContractJsonSerializerSettings.UseSimpleDictionaryFormat
  langs:
  - csharp
  - vb
  name: DataContractJsonSerializerSettings
  nameWithType: DataContractJsonSerializerSettings
  fullName: System.Runtime.Serialization.Json.DataContractJsonSerializerSettings
  type: Class
  source:
    remote:
      path: src/System.Runtime.Serialization.Json/ref/System.Runtime.Serialization.Json.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: DataContractJsonSerializerSettings
    path: src/System.Runtime.Serialization.Json/ref/System.Runtime.Serialization.Json.cs
    startLine: 40
  assemblies:
  - System.Runtime.Serialization.Json
  namespace: System.Runtime.Serialization.Json
  syntax:
    content: 'public class DataContractJsonSerializerSettings : object'
    content.vb: >-
      Public Class DataContractJsonSerializerSettings
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: System.Runtime.Serialization.Json.DataContractJsonSerializerSettings.#ctor
  commentId: M:System.Runtime.Serialization.Json.DataContractJsonSerializerSettings.#ctor
  id: '#ctor'
  parent: System.Runtime.Serialization.Json.DataContractJsonSerializerSettings
  langs:
  - csharp
  - vb
  name: DataContractJsonSerializerSettings()
  nameWithType: DataContractJsonSerializerSettings.DataContractJsonSerializerSettings()
  fullName: System.Runtime.Serialization.Json.DataContractJsonSerializerSettings.DataContractJsonSerializerSettings()
  type: Constructor
  source:
    remote:
      path: src/System.Runtime.Serialization.Json/ref/System.Runtime.Serialization.Json.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: .ctor
    path: src/System.Runtime.Serialization.Json/ref/System.Runtime.Serialization.Json.cs
    startLine: 42
  assemblies:
  - System.Runtime.Serialization.Json
  namespace: System.Runtime.Serialization.Json
  syntax:
    content: public DataContractJsonSerializerSettings()
    content.vb: Public Sub New
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: System.Runtime.Serialization.Json.DataContractJsonSerializerSettings.DateTimeFormat
  commentId: P:System.Runtime.Serialization.Json.DataContractJsonSerializerSettings.DateTimeFormat
  id: DateTimeFormat
  parent: System.Runtime.Serialization.Json.DataContractJsonSerializerSettings
  langs:
  - csharp
  - vb
  name: DateTimeFormat
  nameWithType: DataContractJsonSerializerSettings.DateTimeFormat
  fullName: System.Runtime.Serialization.Json.DataContractJsonSerializerSettings.DateTimeFormat
  type: Property
  source:
    remote:
      path: src/System.Runtime.Serialization.Json/ref/System.Runtime.Serialization.Json.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: DateTimeFormat
    path: src/System.Runtime.Serialization.Json/ref/System.Runtime.Serialization.Json.cs
    startLine: 43
  assemblies:
  - System.Runtime.Serialization.Json
  namespace: System.Runtime.Serialization.Json
  syntax:
    content: public DateTimeFormat DateTimeFormat { get; set; }
    content.vb: Public Property DateTimeFormat As DateTimeFormat
    parameters: []
    return:
      type: System.Runtime.Serialization.DateTimeFormat
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: System.Runtime.Serialization.Json.DataContractJsonSerializerSettings.EmitTypeInformation
  commentId: P:System.Runtime.Serialization.Json.DataContractJsonSerializerSettings.EmitTypeInformation
  id: EmitTypeInformation
  parent: System.Runtime.Serialization.Json.DataContractJsonSerializerSettings
  langs:
  - csharp
  - vb
  name: EmitTypeInformation
  nameWithType: DataContractJsonSerializerSettings.EmitTypeInformation
  fullName: System.Runtime.Serialization.Json.DataContractJsonSerializerSettings.EmitTypeInformation
  type: Property
  source:
    remote:
      path: src/System.Runtime.Serialization.Json/ref/System.Runtime.Serialization.Json.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: EmitTypeInformation
    path: src/System.Runtime.Serialization.Json/ref/System.Runtime.Serialization.Json.cs
    startLine: 44
  assemblies:
  - System.Runtime.Serialization.Json
  namespace: System.Runtime.Serialization.Json
  syntax:
    content: public EmitTypeInformation EmitTypeInformation { get; set; }
    content.vb: Public Property EmitTypeInformation As EmitTypeInformation
    parameters: []
    return:
      type: System.Runtime.Serialization.EmitTypeInformation
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: System.Runtime.Serialization.Json.DataContractJsonSerializerSettings.KnownTypes
  commentId: P:System.Runtime.Serialization.Json.DataContractJsonSerializerSettings.KnownTypes
  id: KnownTypes
  parent: System.Runtime.Serialization.Json.DataContractJsonSerializerSettings
  langs:
  - csharp
  - vb
  name: KnownTypes
  nameWithType: DataContractJsonSerializerSettings.KnownTypes
  fullName: System.Runtime.Serialization.Json.DataContractJsonSerializerSettings.KnownTypes
  type: Property
  source:
    remote:
      path: src/System.Runtime.Serialization.Json/ref/System.Runtime.Serialization.Json.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: KnownTypes
    path: src/System.Runtime.Serialization.Json/ref/System.Runtime.Serialization.Json.cs
    startLine: 45
  assemblies:
  - System.Runtime.Serialization.Json
  namespace: System.Runtime.Serialization.Json
  syntax:
    content: public Collections.Generic.IEnumerable<Type> KnownTypes { get; set; }
    content.vb: Public Property KnownTypes As Collections.Generic.IEnumerable(Of Type)
    parameters: []
    return:
      type: System.Collections.Generic.IEnumerable{System.Type}
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: System.Runtime.Serialization.Json.DataContractJsonSerializerSettings.MaxItemsInObjectGraph
  commentId: P:System.Runtime.Serialization.Json.DataContractJsonSerializerSettings.MaxItemsInObjectGraph
  id: MaxItemsInObjectGraph
  parent: System.Runtime.Serialization.Json.DataContractJsonSerializerSettings
  langs:
  - csharp
  - vb
  name: MaxItemsInObjectGraph
  nameWithType: DataContractJsonSerializerSettings.MaxItemsInObjectGraph
  fullName: System.Runtime.Serialization.Json.DataContractJsonSerializerSettings.MaxItemsInObjectGraph
  type: Property
  source:
    remote:
      path: src/System.Runtime.Serialization.Json/ref/System.Runtime.Serialization.Json.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: MaxItemsInObjectGraph
    path: src/System.Runtime.Serialization.Json/ref/System.Runtime.Serialization.Json.cs
    startLine: 46
  assemblies:
  - System.Runtime.Serialization.Json
  namespace: System.Runtime.Serialization.Json
  syntax:
    content: public int MaxItemsInObjectGraph { get; set; }
    content.vb: Public Property MaxItemsInObjectGraph As Integer
    parameters: []
    return:
      type: System.Int32
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: System.Runtime.Serialization.Json.DataContractJsonSerializerSettings.RootName
  commentId: P:System.Runtime.Serialization.Json.DataContractJsonSerializerSettings.RootName
  id: RootName
  parent: System.Runtime.Serialization.Json.DataContractJsonSerializerSettings
  langs:
  - csharp
  - vb
  name: RootName
  nameWithType: DataContractJsonSerializerSettings.RootName
  fullName: System.Runtime.Serialization.Json.DataContractJsonSerializerSettings.RootName
  type: Property
  source:
    remote:
      path: src/System.Runtime.Serialization.Json/ref/System.Runtime.Serialization.Json.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: RootName
    path: src/System.Runtime.Serialization.Json/ref/System.Runtime.Serialization.Json.cs
    startLine: 47
  assemblies:
  - System.Runtime.Serialization.Json
  namespace: System.Runtime.Serialization.Json
  syntax:
    content: public string RootName { get; set; }
    content.vb: Public Property RootName As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: System.Runtime.Serialization.Json.DataContractJsonSerializerSettings.SerializeReadOnlyTypes
  commentId: P:System.Runtime.Serialization.Json.DataContractJsonSerializerSettings.SerializeReadOnlyTypes
  id: SerializeReadOnlyTypes
  parent: System.Runtime.Serialization.Json.DataContractJsonSerializerSettings
  langs:
  - csharp
  - vb
  name: SerializeReadOnlyTypes
  nameWithType: DataContractJsonSerializerSettings.SerializeReadOnlyTypes
  fullName: System.Runtime.Serialization.Json.DataContractJsonSerializerSettings.SerializeReadOnlyTypes
  type: Property
  source:
    remote:
      path: src/System.Runtime.Serialization.Json/ref/System.Runtime.Serialization.Json.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: SerializeReadOnlyTypes
    path: src/System.Runtime.Serialization.Json/ref/System.Runtime.Serialization.Json.cs
    startLine: 48
  assemblies:
  - System.Runtime.Serialization.Json
  namespace: System.Runtime.Serialization.Json
  syntax:
    content: public bool SerializeReadOnlyTypes { get; set; }
    content.vb: Public Property SerializeReadOnlyTypes As Boolean
    parameters: []
    return:
      type: System.Boolean
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: System.Runtime.Serialization.Json.DataContractJsonSerializerSettings.UseSimpleDictionaryFormat
  commentId: P:System.Runtime.Serialization.Json.DataContractJsonSerializerSettings.UseSimpleDictionaryFormat
  id: UseSimpleDictionaryFormat
  parent: System.Runtime.Serialization.Json.DataContractJsonSerializerSettings
  langs:
  - csharp
  - vb
  name: UseSimpleDictionaryFormat
  nameWithType: DataContractJsonSerializerSettings.UseSimpleDictionaryFormat
  fullName: System.Runtime.Serialization.Json.DataContractJsonSerializerSettings.UseSimpleDictionaryFormat
  type: Property
  source:
    remote:
      path: src/System.Runtime.Serialization.Json/ref/System.Runtime.Serialization.Json.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: UseSimpleDictionaryFormat
    path: src/System.Runtime.Serialization.Json/ref/System.Runtime.Serialization.Json.cs
    startLine: 49
  assemblies:
  - System.Runtime.Serialization.Json
  namespace: System.Runtime.Serialization.Json
  syntax:
    content: public bool UseSimpleDictionaryFormat { get; set; }
    content.vb: Public Property UseSimpleDictionaryFormat As Boolean
    parameters: []
    return:
      type: System.Boolean
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: System.Runtime.Serialization.Json
  commentId: N:System.Runtime.Serialization.Json
  isExternal: false
  name: System.Runtime.Serialization.Json
  nameWithType: System.Runtime.Serialization.Json
  fullName: System.Runtime.Serialization.Json
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: System.Runtime.Serialization.DateTimeFormat
  commentId: T:System.Runtime.Serialization.DateTimeFormat
  parent: System.Runtime.Serialization
  isExternal: false
  name: DateTimeFormat
  nameWithType: DateTimeFormat
  fullName: System.Runtime.Serialization.DateTimeFormat
- uid: System.Runtime.Serialization
  commentId: N:System.Runtime.Serialization
  isExternal: false
  name: System.Runtime.Serialization
  nameWithType: System.Runtime.Serialization
  fullName: System.Runtime.Serialization
- uid: System.Runtime.Serialization.EmitTypeInformation
  commentId: T:System.Runtime.Serialization.EmitTypeInformation
  parent: System.Runtime.Serialization
  isExternal: false
  name: EmitTypeInformation
  nameWithType: EmitTypeInformation
  fullName: System.Runtime.Serialization.EmitTypeInformation
- uid: System.Collections.Generic.IEnumerable{System.Type}
  commentId: '!:System.Collections.Generic.IEnumerable{System.Type}'
  definition: System.Collections.Generic.IEnumerable`1
  name: Collections.Generic.IEnumerable<Type>
  nameWithType: Collections.Generic.IEnumerable<Type>
  fullName: System.Collections.Generic.IEnumerable<System.Type>
  nameWithType.vb: Collections.Generic.IEnumerable(Of Type)
  fullname.vb: System.Collections.Generic.IEnumerable(Of System.Type)
  name.vb: Collections.Generic.IEnumerable(Of Type)
  spec.csharp:
  - uid: System.Collections.Generic.IEnumerable`1
    name: Collections.Generic.IEnumerable
    nameWithType: Collections.Generic.IEnumerable
    fullName: System.Collections.Generic.IEnumerable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.Type
    name: Type
    nameWithType: Type
    fullName: System.Type
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IEnumerable`1
    name: Collections.Generic.IEnumerable
    nameWithType: Collections.Generic.IEnumerable
    fullName: System.Collections.Generic.IEnumerable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.Type
    name: Type
    nameWithType: Type
    fullName: System.Type
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Collections.Generic.IEnumerable`1
  commentId: T:System.Collections.Generic.IEnumerable`1
  isExternal: false
  name: Collections.Generic.IEnumerable<>
  nameWithType: Collections.Generic.IEnumerable<>
  fullName: System.Collections.Generic.IEnumerable<>
  nameWithType.vb: Collections.Generic.IEnumerable(Of )
  fullname.vb: System.Collections.Generic.IEnumerable(Of )
  name.vb: Collections.Generic.IEnumerable(Of )
  spec.csharp:
  - uid: System.Collections.Generic.IEnumerable`1
    name: Collections.Generic.IEnumerable
    nameWithType: Collections.Generic.IEnumerable
    fullName: System.Collections.Generic.IEnumerable
  - name: <
    nameWithType: <
    fullName: <
  - name: 
    nameWithType: 
    fullName: 
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Generic.IEnumerable`1
    name: Collections.Generic.IEnumerable
    nameWithType: Collections.Generic.IEnumerable
    fullName: System.Collections.Generic.IEnumerable
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: 
    nameWithType: 
    fullName: 
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: false
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
