items:
- uid: System.Environment
  commentId: T:System.Environment
  id: Environment
  parent: System
  children:
  - System.Environment.CurrentManagedThreadId
  - System.Environment.Exit(System.Int32)
  - System.Environment.ExpandEnvironmentVariables(System.String)
  - System.Environment.FailFast(System.String)
  - System.Environment.FailFast(System.String,System.Exception)
  - System.Environment.GetCommandLineArgs
  - System.Environment.GetEnvironmentVariable(System.String)
  - System.Environment.GetEnvironmentVariables
  - System.Environment.HasShutdownStarted
  - System.Environment.MachineName
  - System.Environment.NewLine
  - System.Environment.ProcessorCount
  - System.Environment.SetEnvironmentVariable(System.String,System.String)
  - System.Environment.StackTrace
  - System.Environment.TickCount
  langs:
  - csharp
  - vb
  name: Environment
  nameWithType: Environment
  fullName: System.Environment
  type: Class
  source:
    remote:
      path: src/System.Runtime.Extensions/ref/System.Runtime.Extensions.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: Environment
    path: src/System.Runtime.Extensions/ref/System.Runtime.Extensions.cs
    startLine: 431
  assemblies:
  - System.Runtime.Extensions
  namespace: System
  syntax:
    content: 'public class Environment : object'
    content.vb: >-
      Public Class Environment
          Inherits Object
  inheritance:
  - System.Object
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: System.Environment.CurrentManagedThreadId
  commentId: P:System.Environment.CurrentManagedThreadId
  id: CurrentManagedThreadId
  parent: System.Environment
  langs:
  - csharp
  - vb
  name: CurrentManagedThreadId
  nameWithType: Environment.CurrentManagedThreadId
  fullName: System.Environment.CurrentManagedThreadId
  type: Property
  source:
    remote:
      path: src/System.Runtime.Extensions/ref/System.Runtime.Extensions.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: CurrentManagedThreadId
    path: src/System.Runtime.Extensions/ref/System.Runtime.Extensions.cs
    startLine: 433
  assemblies:
  - System.Runtime.Extensions
  namespace: System
  syntax:
    content: public static int CurrentManagedThreadId { get; }
    content.vb: Public Shared ReadOnly Property CurrentManagedThreadId As Integer
    parameters: []
    return:
      type: System.Int32
  modifiers.csharp:
  - public
  - static
  - get
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
- uid: System.Environment.HasShutdownStarted
  commentId: P:System.Environment.HasShutdownStarted
  id: HasShutdownStarted
  parent: System.Environment
  langs:
  - csharp
  - vb
  name: HasShutdownStarted
  nameWithType: Environment.HasShutdownStarted
  fullName: System.Environment.HasShutdownStarted
  type: Property
  source:
    remote:
      path: src/System.Runtime.Extensions/ref/System.Runtime.Extensions.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: HasShutdownStarted
    path: src/System.Runtime.Extensions/ref/System.Runtime.Extensions.cs
    startLine: 434
  assemblies:
  - System.Runtime.Extensions
  namespace: System
  syntax:
    content: public static bool HasShutdownStarted { get; }
    content.vb: Public Shared ReadOnly Property HasShutdownStarted As Boolean
    parameters: []
    return:
      type: System.Boolean
  modifiers.csharp:
  - public
  - static
  - get
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
- uid: System.Environment.MachineName
  commentId: P:System.Environment.MachineName
  id: MachineName
  parent: System.Environment
  langs:
  - csharp
  - vb
  name: MachineName
  nameWithType: Environment.MachineName
  fullName: System.Environment.MachineName
  type: Property
  source:
    remote:
      path: src/System.Runtime.Extensions/ref/System.Runtime.Extensions.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: MachineName
    path: src/System.Runtime.Extensions/ref/System.Runtime.Extensions.cs
    startLine: 435
  assemblies:
  - System.Runtime.Extensions
  namespace: System
  syntax:
    content: public static string MachineName { get; }
    content.vb: Public Shared ReadOnly Property MachineName As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - static
  - get
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
- uid: System.Environment.NewLine
  commentId: P:System.Environment.NewLine
  id: NewLine
  parent: System.Environment
  langs:
  - csharp
  - vb
  name: NewLine
  nameWithType: Environment.NewLine
  fullName: System.Environment.NewLine
  type: Property
  source:
    remote:
      path: src/System.Runtime.Extensions/ref/System.Runtime.Extensions.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: NewLine
    path: src/System.Runtime.Extensions/ref/System.Runtime.Extensions.cs
    startLine: 436
  assemblies:
  - System.Runtime.Extensions
  namespace: System
  syntax:
    content: public static string NewLine { get; }
    content.vb: Public Shared ReadOnly Property NewLine As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - static
  - get
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
- uid: System.Environment.ProcessorCount
  commentId: P:System.Environment.ProcessorCount
  id: ProcessorCount
  parent: System.Environment
  langs:
  - csharp
  - vb
  name: ProcessorCount
  nameWithType: Environment.ProcessorCount
  fullName: System.Environment.ProcessorCount
  type: Property
  source:
    remote:
      path: src/System.Runtime.Extensions/ref/System.Runtime.Extensions.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: ProcessorCount
    path: src/System.Runtime.Extensions/ref/System.Runtime.Extensions.cs
    startLine: 437
  assemblies:
  - System.Runtime.Extensions
  namespace: System
  syntax:
    content: public static int ProcessorCount { get; }
    content.vb: Public Shared ReadOnly Property ProcessorCount As Integer
    parameters: []
    return:
      type: System.Int32
  modifiers.csharp:
  - public
  - static
  - get
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
- uid: System.Environment.StackTrace
  commentId: P:System.Environment.StackTrace
  id: StackTrace
  parent: System.Environment
  langs:
  - csharp
  - vb
  name: StackTrace
  nameWithType: Environment.StackTrace
  fullName: System.Environment.StackTrace
  type: Property
  source:
    remote:
      path: src/System.Runtime.Extensions/ref/System.Runtime.Extensions.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: StackTrace
    path: src/System.Runtime.Extensions/ref/System.Runtime.Extensions.cs
    startLine: 438
  assemblies:
  - System.Runtime.Extensions
  namespace: System
  syntax:
    content: public static string StackTrace { get; }
    content.vb: Public Shared ReadOnly Property StackTrace As String
    parameters: []
    return:
      type: System.String
  modifiers.csharp:
  - public
  - static
  - get
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
- uid: System.Environment.TickCount
  commentId: P:System.Environment.TickCount
  id: TickCount
  parent: System.Environment
  langs:
  - csharp
  - vb
  name: TickCount
  nameWithType: Environment.TickCount
  fullName: System.Environment.TickCount
  type: Property
  source:
    remote:
      path: src/System.Runtime.Extensions/ref/System.Runtime.Extensions.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: TickCount
    path: src/System.Runtime.Extensions/ref/System.Runtime.Extensions.cs
    startLine: 439
  assemblies:
  - System.Runtime.Extensions
  namespace: System
  syntax:
    content: public static int TickCount { get; }
    content.vb: Public Shared ReadOnly Property TickCount As Integer
    parameters: []
    return:
      type: System.Int32
  modifiers.csharp:
  - public
  - static
  - get
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
- uid: System.Environment.ExpandEnvironmentVariables(System.String)
  commentId: M:System.Environment.ExpandEnvironmentVariables(System.String)
  id: ExpandEnvironmentVariables(System.String)
  parent: System.Environment
  langs:
  - csharp
  - vb
  name: ExpandEnvironmentVariables(String)
  nameWithType: Environment.ExpandEnvironmentVariables(String)
  fullName: System.Environment.ExpandEnvironmentVariables(System.String)
  type: Method
  source:
    remote:
      path: src/System.Runtime.Extensions/ref/System.Runtime.Extensions.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: ExpandEnvironmentVariables
    path: src/System.Runtime.Extensions/ref/System.Runtime.Extensions.cs
    startLine: 440
  assemblies:
  - System.Runtime.Extensions
  namespace: System
  syntax:
    content: public static string ExpandEnvironmentVariables(string name)
    content.vb: Public Shared Function ExpandEnvironmentVariables(name As String) As String
    parameters:
    - id: name
      type: System.String
    return:
      type: System.String
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
- uid: System.Environment.Exit(System.Int32)
  commentId: M:System.Environment.Exit(System.Int32)
  id: Exit(System.Int32)
  parent: System.Environment
  langs:
  - csharp
  - vb
  name: Exit(Int32)
  nameWithType: Environment.Exit(Int32)
  fullName: System.Environment.Exit(System.Int32)
  type: Method
  source:
    remote:
      path: src/System.Runtime.Extensions/ref/System.Runtime.Extensions.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: Exit
    path: src/System.Runtime.Extensions/ref/System.Runtime.Extensions.cs
    startLine: 441
  assemblies:
  - System.Runtime.Extensions
  namespace: System
  syntax:
    content: public static void Exit(int exitCode)
    content.vb: Public Shared Sub Exit(exitCode As Integer)
    parameters:
    - id: exitCode
      type: System.Int32
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
- uid: System.Environment.FailFast(System.String)
  commentId: M:System.Environment.FailFast(System.String)
  id: FailFast(System.String)
  parent: System.Environment
  langs:
  - csharp
  - vb
  name: FailFast(String)
  nameWithType: Environment.FailFast(String)
  fullName: System.Environment.FailFast(System.String)
  type: Method
  source:
    remote:
      path: src/System.Runtime.Extensions/ref/System.Runtime.Extensions.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: FailFast
    path: src/System.Runtime.Extensions/ref/System.Runtime.Extensions.cs
    startLine: 442
  assemblies:
  - System.Runtime.Extensions
  namespace: System
  syntax:
    content: public static void FailFast(string message)
    content.vb: Public Shared Sub FailFast(message As String)
    parameters:
    - id: message
      type: System.String
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
- uid: System.Environment.FailFast(System.String,System.Exception)
  commentId: M:System.Environment.FailFast(System.String,System.Exception)
  id: FailFast(System.String,System.Exception)
  parent: System.Environment
  langs:
  - csharp
  - vb
  name: FailFast(String, Exception)
  nameWithType: Environment.FailFast(String, Exception)
  fullName: System.Environment.FailFast(System.String, System.Exception)
  type: Method
  source:
    remote:
      path: src/System.Runtime.Extensions/ref/System.Runtime.Extensions.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: FailFast
    path: src/System.Runtime.Extensions/ref/System.Runtime.Extensions.cs
    startLine: 444
  assemblies:
  - System.Runtime.Extensions
  namespace: System
  syntax:
    content: public static void FailFast(string message, Exception exception)
    content.vb: Public Shared Sub FailFast(message As String, exception As Exception)
    parameters:
    - id: message
      type: System.String
    - id: exception
      type: System.Exception
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
- uid: System.Environment.GetEnvironmentVariable(System.String)
  commentId: M:System.Environment.GetEnvironmentVariable(System.String)
  id: GetEnvironmentVariable(System.String)
  parent: System.Environment
  langs:
  - csharp
  - vb
  name: GetEnvironmentVariable(String)
  nameWithType: Environment.GetEnvironmentVariable(String)
  fullName: System.Environment.GetEnvironmentVariable(System.String)
  type: Method
  source:
    remote:
      path: src/System.Runtime.Extensions/ref/System.Runtime.Extensions.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: GetEnvironmentVariable
    path: src/System.Runtime.Extensions/ref/System.Runtime.Extensions.cs
    startLine: 446
  assemblies:
  - System.Runtime.Extensions
  namespace: System
  syntax:
    content: public static string GetEnvironmentVariable(string variable)
    content.vb: Public Shared Function GetEnvironmentVariable(variable As String) As String
    parameters:
    - id: variable
      type: System.String
    return:
      type: System.String
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
- uid: System.Environment.GetEnvironmentVariables
  commentId: M:System.Environment.GetEnvironmentVariables
  id: GetEnvironmentVariables
  parent: System.Environment
  langs:
  - csharp
  - vb
  name: GetEnvironmentVariables()
  nameWithType: Environment.GetEnvironmentVariables()
  fullName: System.Environment.GetEnvironmentVariables()
  type: Method
  source:
    remote:
      path: src/System.Runtime.Extensions/ref/System.Runtime.Extensions.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: GetEnvironmentVariables
    path: src/System.Runtime.Extensions/ref/System.Runtime.Extensions.cs
    startLine: 447
  assemblies:
  - System.Runtime.Extensions
  namespace: System
  syntax:
    content: public static Collections.IDictionary GetEnvironmentVariables()
    content.vb: Public Shared Function GetEnvironmentVariables As Collections.IDictionary
    return:
      type: System.Collections.IDictionary
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
- uid: System.Environment.SetEnvironmentVariable(System.String,System.String)
  commentId: M:System.Environment.SetEnvironmentVariable(System.String,System.String)
  id: SetEnvironmentVariable(System.String,System.String)
  parent: System.Environment
  langs:
  - csharp
  - vb
  name: SetEnvironmentVariable(String, String)
  nameWithType: Environment.SetEnvironmentVariable(String, String)
  fullName: System.Environment.SetEnvironmentVariable(System.String, System.String)
  type: Method
  source:
    remote:
      path: src/System.Runtime.Extensions/ref/System.Runtime.Extensions.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: SetEnvironmentVariable
    path: src/System.Runtime.Extensions/ref/System.Runtime.Extensions.cs
    startLine: 448
  assemblies:
  - System.Runtime.Extensions
  namespace: System
  syntax:
    content: public static void SetEnvironmentVariable(string variable, string value)
    content.vb: Public Shared Sub SetEnvironmentVariable(variable As String, value As String)
    parameters:
    - id: variable
      type: System.String
    - id: value
      type: System.String
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
- uid: System.Environment.GetCommandLineArgs
  commentId: M:System.Environment.GetCommandLineArgs
  id: GetCommandLineArgs
  parent: System.Environment
  langs:
  - csharp
  - vb
  name: GetCommandLineArgs()
  nameWithType: Environment.GetCommandLineArgs()
  fullName: System.Environment.GetCommandLineArgs()
  type: Method
  source:
    remote:
      path: src/System.Runtime.Extensions/ref/System.Runtime.Extensions.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    id: GetCommandLineArgs
    path: src/System.Runtime.Extensions/ref/System.Runtime.Extensions.cs
    startLine: 449
  assemblies:
  - System.Runtime.Extensions
  namespace: System
  syntax:
    content: public static string[] GetCommandLineArgs()
    content.vb: Public Shared Function GetCommandLineArgs As String()
    return:
      type: System.String[]
  modifiers.csharp:
  - public
  - static
  modifiers.vb:
  - Public
  - Shared
references:
- uid: System
  commentId: N:System
  isExternal: false
  name: System
  nameWithType: System
  fullName: System
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: false
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: false
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Boolean
  commentId: T:System.Boolean
  parent: System
  isExternal: false
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: false
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Exception
  commentId: T:System.Exception
  parent: System
  isExternal: false
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Collections.IDictionary
  commentId: T:System.Collections.IDictionary
  parent: System.Collections
  isExternal: false
  name: Collections.IDictionary
  nameWithType: Collections.IDictionary
  fullName: System.Collections.IDictionary
- uid: System.Collections
  commentId: N:System.Collections
  isExternal: false
  name: System.Collections
  nameWithType: System.Collections
  fullName: System.Collections
- uid: System.String[]
  name: String[]
  nameWithType: String[]
  fullName: System.String[]
  nameWithType.vb: String()
  fullname.vb: System.String()
  name.vb: String()
  spec.csharp:
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
  - name: '[]'
    nameWithType: '[]'
    fullName: '[]'
  spec.vb:
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
  - name: ()
    nameWithType: ()
    fullName: ()
