items:
- uid: System.Security
  id: System.Security
  children:
  - System.Security.AllowPartiallyTrustedCallersAttribute
  - System.Security.SecurityCriticalAttribute
  - System.Security.SecurityException
  - System.Security.SecuritySafeCriticalAttribute
  - System.Security.SecurityTransparentAttribute
  - System.Security.VerificationException
  name: System.Security
  fullName: System.Security
  type: Namespace
  source:
    remote:
      path: src/mscorlib/src/System/Security/AccessControl/Enums.cs
      branch: master
      repo: https://github.com/dotnet/coreclr.git
    path: src/mscorlib/src/System/Security/AccessControl/Enums.cs
    startLine: 6
  assemblies:
  - System.Runtime
  summary: The <xref href="System.Security" data-throw-if-not-resolved="false"></xref> namespace provides the underlying structure of the common language runtime security system, including base classes for permissions.
references:
- uid: System.Security.AllowPartiallyTrustedCallersAttribute
  isExternal: false
  name: AllowPartiallyTrustedCallersAttribute
  fullName: System.Security.AllowPartiallyTrustedCallersAttribute
- uid: System.Security.SecurityCriticalAttribute
  isExternal: false
  name: SecurityCriticalAttribute
  fullName: System.Security.SecurityCriticalAttribute
- uid: System.Security.SecurityException
  isExternal: false
  name: SecurityException
  fullName: System.Security.SecurityException
- uid: System.Security.SecuritySafeCriticalAttribute
  isExternal: false
  name: SecuritySafeCriticalAttribute
  fullName: System.Security.SecuritySafeCriticalAttribute
- uid: System.Security.SecurityTransparentAttribute
  isExternal: false
  name: SecurityTransparentAttribute
  fullName: System.Security.SecurityTransparentAttribute
- uid: System.Security.VerificationException
  isExternal: false
  name: VerificationException
  fullName: System.Security.VerificationException
