items:
- uid: System.Data.SqlClient.ApplicationIntent
  id: ApplicationIntent
  parent: System.Data.SqlClient
  children:
  - System.Data.SqlClient.ApplicationIntent.ReadOnly
  - System.Data.SqlClient.ApplicationIntent.ReadWrite
  name: ApplicationIntent
  fullName: System.Data.SqlClient.ApplicationIntent
  type: Enum
  source:
    remote: &o0
      path: src/System.Data.SqlClient/src/System/Data/SqlClient/ApplicationIntent.cs
      branch: master
      repo: https://github.com/dotnet/corefx.git
    path: src/System.Data.SqlClient/src/System/Data/SqlClient/ApplicationIntent.cs
    startLine: 12
  assemblies:
  - System.Data.SqlClient
  namespace: System.Data.SqlClient
  summary: Specifies a value for <xref href="System.Data.SqlClient.SqlConnectionStringBuilder.ApplicationIntent" data-throw-if-not-resolved="false"></xref>. Possible values are ReadWrite and ReadOnly.
  syntax:
    content: 'public enum ApplicationIntent : int'
    content.vb: Public Enum ApplicationIntent As Integer
- uid: System.Data.SqlClient.ApplicationIntent.ReadOnly
  id: ReadOnly
  parent: System.Data.SqlClient.ApplicationIntent
  name: ReadOnly
  fullName: System.Data.SqlClient.ApplicationIntent.ReadOnly
  type: Field
  source:
    remote: *o0
    path: src/System.Data.SqlClient/src/System/Data/SqlClient/ApplicationIntent.cs
    startLine: 15
  assemblies:
  - System.Data.SqlClient
  namespace: System.Data.SqlClient
  summary: The application workload type when connecting to a server is read only.
  syntax:
    content: ReadOnly = null
    content.vb: ReadOnly = Nothing
- uid: System.Data.SqlClient.ApplicationIntent.ReadWrite
  id: ReadWrite
  parent: System.Data.SqlClient.ApplicationIntent
  name: ReadWrite
  fullName: System.Data.SqlClient.ApplicationIntent.ReadWrite
  type: Field
  source:
    remote: *o0
    path: src/System.Data.SqlClient/src/System/Data/SqlClient/ApplicationIntent.cs
    startLine: 14
  assemblies:
  - System.Data.SqlClient
  namespace: System.Data.SqlClient
  summary: The application workload type when connecting to a server is read write.
  syntax:
    content: ReadWrite = null
    content.vb: ReadWrite = Nothing
references:
- uid: System.Data.SqlClient
  isExternal: false
  name: System.Data.SqlClient
  fullName: System.Data.SqlClient
